"""empty message

Revision ID: 5d2a00ab58b9
Revises: 44ebc8f074f2
Create Date: 2017-05-18 15:05:44.989365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d2a00ab58b9'
down_revision = '44ebc8f074f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'msg_text',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'msg_text',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
